name: plant_disease_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
      - torch==2.1.0
      - torchvision==0.16.0
      - pillow==10.1.0
      - numpy==1.24.3
      - pandas==2.1.3
      - scikit-learn==1.3.2
      - mlflow==2.8.1
      - azureml-mlflow==1.54.0
      - opencv-python==4.8.1.78
      - pyyaml==6.0.1
      - tqdm==4.66.1
